name: cosdart
description: Contentos blockchain SDK for Dart.
version: 0.0.1
author: daishuo@gmail.com
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pointycastle: "^1.0.2"

dev_dependencies:
  test: "^1.10.0"
